AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Guardfile
  Exclude:
    - vendor/**/*
    - cookbooks/**/*
  TargetRubyVersion: 2.3

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
SignalException:
  Enabled: false
WordArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# Use until migration to classes
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
